# Logits Preprocessing and Data Engineering

In [ ]:
def default_params(): 
    return {
        'current_model': 'M1', 
        'quantization': 'none', #['none',"int4", "int8", "float32", "float16"]
        'dataset': {
            'path': '/workspaces/CodeSmells/data/extension/mitigation/datasets',
            'current': 'prompted', # 'base' or 'prompted',
            'content_column': 'code',
            'sampling_size': 500,
            'prompt_column': 'prompt',
        },
        'logging_path': '/workspaces/CodeSmells/datax/code_smells/logs', 
        'output_path' : '/workspaces/CodeSmells/datax/code_smells/logits/mitigation',
        'callbacks_path' : '/workspaces/CodeSmells/datax/code_smells/callbacks/mitigation',
        'cache_dir': '/workspaces/CodeSmells/datax/hugging_face_cache',
        'causal_models': {
            ##### BY ARCHITECTURE, SAME SIZE #####
            'M1' : 'codellama/CodeLlama-7b-hf', #https://huggingface.co/codellama/CodeLlama-7b-hf, 
            'M2' : 'mistralai/Mistral-7B-v0.3', #https://huggingface.co/mistralai/Mistral-7B-v0.3,
            'M3' : 'Qwen/Qwen2.5-Coder-7B', #https://huggingface.co/Qwen/Qwen2.5-Coder-7B,
            'M4' : 'bigcode/starcoder2-7b', #https://huggingface.co/bigcode/starcoder2-7b,
            ##### BY SIZE, SAME ARCHITECTURE #####
            'S1' : 'Qwen/Qwen2.5-Coder-0.5B', #https://huggingface.co/Qwen/Qwen2.5-Coder-0.5B,
            'S2' : 'Qwen/Qwen2.5-Coder-1.5B', #https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B,
            'S3' : 'Qwen/Qwen2.5-Coder-3B', #https://huggingface.co/Qwen/Qwen2.5-Coder-3B,
            'S4' : 'Qwen/Qwen2.5-Coder-7B', #https://huggingface.co/Qwen/Qwen2.5-Coder-7B,
        },
    }
params = default_params()

#### Imports

In [2]:
import pandas as pd
import os
import time
import numpy as np
import torch
import gc

In [3]:
import seaborn as sns
from scipy import stats
from statistics import NormalDist
import matplotlib.pyplot as plt

In [4]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset

In [5]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [6]:
# Define log file path
log_file = f"{params['logging_path']}/{params['current_model']}"
create_folder(log_file)
log_file += '/data_en.txt'

# Create the log file if it doesn't exist
if not os.path.exists(log_file):
    with open(log_file, 'w'): 
        pass  # Create an empty log file

In [7]:
import logging
logging.basicConfig(filename=log_file, format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

#### Dataset

In [8]:
print(f"{params['dataset']['path']}/{params['dataset']['current']}.json")

/workspaces/CodeSmells/data/extension/mitigation/datasets/base.json

In [9]:
df_dataset = pd.read_json(f"{params['dataset']['path']}/{params['dataset']['current']}.json", )

In [10]:
df_dataset

,id,commit_id,repo,path,file_name,fun_name,commit_message,code,url,language,...,n_ast_nodes,n_identifiers,s_msg_id,s_line,s_column,s_end_line,s_end_column,s_code,category,input_lenght
0,278224,ebb5e0e3f5e0b02cad2b54144022084301588ac5,keras,keras/mixed_precision/loss_scale_optimizer_tes...,loss_scale_optimizer_test.py,testHyperParametersExposed,resolve line-too-long in mixed_precision,def testHyperParametersExposed(self):\n ...,https://github.com/keras-team/keras.git,Python,...,456,22,C0304,30,0,30,73,# LossScaleOptimizer and hyperpara...,Convention,536
1,276644,84afc5193d38057e2e2badf9c889ea87d80d8fbf,keras,keras/tests/tracking_util_with_v1_optimizers_t...,tracking_util_with_v1_optimizers_test.py,__init__,Reformatting the codebase with black.\n\nPiper...,def __init__(self):\n super().__init__(...,https://github.com/keras-team/keras.git,Python,...,53,8,C0304,7,0,7,30,# pylint: disable=not-callable,Convention,62
2,24968,1a0a75e3fa896cf3c095e4146a54acef7223657e,PaddleOCR,ppstructure/pdf2word/pdf2word.py,pdf2word.py,predictAndSave,Add pdf2word exe\n\nAdd pdf2word exe,"def predictAndSave(self, imgs, img_name):\r\n ...",https://github.com/PaddlePaddle/PaddleOCR.git,Python,...,251,34,C0304,25,0,25,0,,Convention,308
3,278875,3613c3defc39c236fb1592c4f7ba1a9cc887343a,keras,keras/mixed_precision/loss_scale_optimizer_tes...,loss_scale_optimizer_test.py,testHyperParametersExposed,Remove pylint comments.\n\nPiperOrigin-RevId: ...,def testHyperParametersExposed(self):\n ...,https://github.com/keras-team/keras.git,Python,...,455,22,C0304,30,0,30,73,# LossScaleOptimizer and hyperpara...,Convention,524
4,152057,a6adc22f0711c8ab78c6ef8fc78715f815cc750f,stable-diffusion-webui,webui.py,webui.py,js,added interrupt button\nadded save button\n--a...,def js(self):\r\n obj = {\r\n ...,https://github.com/AUTOMATIC1111/stable-diffus...,Python,...,102,13,C0304,11,0,11,30,return json.dumps(obj),Convention,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,115229,4f2861b6ded274d4a41322c107ace8107e86ebea,mindsdb,mindsdb/interfaces/database/views.py,views.py,add,store integration in sql of view (before save it),"def add(self, name, query, integration_name, c...",https://github.com/mindsdb/mindsdb.git,Python,...,247,25,W0719,21,16,21,88,"raise Exception(f""Can't find integration with ...",Warning,264
1496,282637,fae93c67adc9015c1466712f9c8ffa35a8b70872,OpenBBTerminal,bots/economy/usbonds.py,usbonds.py,usbonds_command,Refactor Bot (#1326)\n\n* First commit\r\n\r\n...,def usbonds_command():\n \n\n # Debug us...,https://github.com/OpenBB-finance/OpenBBTermin...,Python,...,469,45,W0719,12,8,12,50,"raise Exception(""No available data found"")",Warning,545
1497,2842,ccd4b9330a186090cc87e94d2da1093d45de329f,PySyft,packages/syft/src/syft/oblv/model.py,model.py,request_publish,Changes for model,"def request_publish(self, dataset_id, sigma = ...",https://github.com/OpenMined/PySyft.git,Python,...,383,31,W0719,2,12,2,116,"raise Exception(""No Domain Clients added. Set ...",Warning,497
1498,116308,326622a6fb33664de21ee1627f5f083f11b59a9e,mindsdb,mindsdb/integrations/handlers/ludwig_handler/l...,ludwig_handler.py,_learn,fix: add hyperopt,"def _learn(self, statement):\n model_na...",https://github.com/mindsdb/mindsdb.git,Python,...,374,50,W0719,8,12,8,85,"raise Exception(""Ludwig handler does not suppo...",Warning,466
1499,115499,a9c93271182d6fa33679d1709f555ef80d71a003,mindsdb,tests/integration_tests/flows/test_mysql_api.py,test_mysql_api.py,check_predictor_readiness,fix,"def check_predictor_readiness(self, predictor_...",https://github.com/mindsdb/mindsdb.git,Python,...,203,14,W0719,11,20,11,52,raise Exception(res[0]['error']),Warning,193

#### Model Loading

In [11]:
def instantiate_llm(model_name:str, cache_dir:str):
     '''Instantiate AutoModelForCausalLM'''
     tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir = cache_dir, use_fast=True)
     logging.info("Loaded AutoTokenizer - " + model_name)
     model = None
     if params['quantization'] == 'int4':
          model = AutoModelForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_4bit=True)
     elif params['quantization'] == 'int8':
          model = AutoModelForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, load_in_8bit=True)
     elif params['quantization'] == 'float32':
          model = AutoModelForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float32)
     elif params['quantization'] == 'float16':
          model = AutoModelForCausalLM.from_pretrained(model_name, cache_dir = cache_dir, torch_dtype=torch.float16)
     else: 
          model = AutoModelForCausalLM.from_pretrained(model_name, cache_dir = cache_dir)
     logging.info("Loaded AutoModelForCausalLM - " + model_name)

     return tokenizer, model

In [12]:
tokenizer, model = instantiate_llm(params['causal_models'][params['current_model']], params['cache_dir'])

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [13]:
print(model.config)
print(model.__class__)
print(tokenizer.__class__)

LlamaConfig {
  "_name_or_path": "codellama/CodeLlama-7b-hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 16384,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 1000000,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.36.2",
  "use_cache": true,
  "vocab_size": 32016
}

<class 'transformers.models.llama.modeling_llama.LlamaForCausalLM'>
<class 'transformers.models.code_llama.tokenization_code_llama_fast.CodeLlamaTokenizerFast'>

#### preprocess dataset

In [14]:
df_dataset['input_ids'] = df_dataset[params['dataset']['content_column']].map(lambda code: tokenizer.encode(code, add_special_tokens=False))
if params['dataset']['current'] == 'prompted':
    df_dataset['prompt_ids'] = df_dataset[params['dataset']['prompt_column']].map(lambda code: tokenizer.encode(code, add_special_tokens=False))
df_dataset['input_lenght'] = df_dataset['input_ids'].map(lambda input_ids: len(input_ids))

#### Softmax Normalization and Data Engineering

In [15]:
def topk_tuple(logit_vocab_tensor, largest, tokenizer_fn):
    """
    Return the decoded top-1 (or bottom-1) token and its logit value.
    """
    topk = logit_vocab_tensor.topk(k=1, largest=largest)
    top_token_id = topk.indices[0].item()
    decoded_token = tokenizer_fn.decode([top_token_id])  # Already handles special tokens and spaces
    return (decoded_token, topk.values[0].item())

In [16]:
def analyze_logits(logit_tensor_sequence, input_token_ids, tokenizer_fn, skip_first_token=True):
    """
    Analyze logits for each token in a sequence.

    Args:
        logit_tensor_sequence (List[Tensor]): List of vocab-sized logits for each token position.
        input_token_ids (List[int] or Tensor): Token IDs of the input prompt.
        tokenizer_fn: HuggingFace tokenizer with .decode() method.
        skip_first_token (bool): Whether to skip the first token prediction (default: True).

    Returns:
        dict with:
            - "max_cases": list of (decoded top-1 token, logit value)
            - "min_cases": list of (decoded bottom-1 token, logit value)
            - "actual_logits": list of (decoded ground-truth token, logit value)
    """
    max_cases = []
    min_cases = []
    actual_logits = []

    start_index = 1 if skip_first_token else 0
    token_targets = input_token_ids[start_index:]

    for position, token_id in enumerate(token_targets):
        vocab_logits = logit_tensor_sequence[position]

        # Top-1 max and min predictions
        max_case = topk_tuple(logit_vocab_tensor=vocab_logits, largest=True, tokenizer_fn=tokenizer_fn)
        min_case = topk_tuple(logit_vocab_tensor=vocab_logits, largest=False, tokenizer_fn=tokenizer_fn)

        # Actual token logit
        decoded_token = tokenizer_fn.decode([int(token_id)])
        logit_value = vocab_logits[int(token_id)].item()
        actual_case = (decoded_token, logit_value)

        max_cases.append(max_case)
        min_cases.append(min_case)
        actual_logits.append(actual_case)

    return {
        "max_cases": max_cases,
        "min_cases": min_cases,
        "actual_logits": actual_logits
    }

In [17]:
soft = torch.nn.Softmax( dim = 0 ) #Flattening normalization

In [18]:
callbacks_dir = f"{params['callbacks_path']}/{params['dataset']['current']}/{params['current_model']}_q_{params['quantization']}"
out = np.load(f"{callbacks_dir}/logits_tensor[0]_batch[0].npy")

print(out.shape) #<sample,tokens,voc_tokens>
out = out[0]

(1, 536, 32016)

In [19]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

logit_dict = analyze_logits(
    logit_tensor_sequence = [ soft( torch.from_numpy(token) ) for token in out] , #Out is a complete sequence
    input_token_ids = input_ids_list[0], ## SAMPLE ID
    tokenizer_fn = tokenizer
)

2025-11-18 19:42:34.661716: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/resource_handle.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor_shape.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/types.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/full_type.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/function.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/node_def.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/op_def.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/graph.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/graph_debug_info.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/versions.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/config.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at xla/tsl/protobuf/coordination_config.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/cost_graph.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/step_stats.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/allocation_description.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor_description.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/cluster.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/debug.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

In [20]:
assert len(set(len(v) for v in logit_dict.values())) == 1, "All key array values in logit_dict do not have the same length"

#### Processing all the Batches

In [21]:
def process_logit_batches(tokenizer, tokenized_inputs, num_samples=10000, skip_first_token=True):
    """
    Process multiple saved logits files and extract:
    - top-1 max logit predictions,
    - top-1 min logit predictions,
    - actual logits for ground-truth tokens.

    Args:
        tokenizer: HuggingFace tokenizer instance.
        tokenized_inputs (List[Tensor]): Tokenized input prompts (one per sample).
        num_samples (int): Number of samples to process.
        skip_first_token (bool): Whether to skip the first token prediction.

    Returns:
        Tuple of lists: (max_logit_predictions, min_logit_predictions, actual_logits)
    """
    max_logit_predictions = []
    min_logit_predictions = []
    actual_logit_scores = []

    softmax_fn = torch.nn.Softmax(dim=0)
    base_path = f"{params['callbacks_path']}/{params['dataset']['current']}/{params['current_model']}_q_{params['quantization']}"

    for sample_idx in range(num_samples):
        logits_file_path = f"{base_path}/logits_tensor[{sample_idx}]_batch[{sample_idx}].npy"
        logits_array = np.load(logits_file_path)[0]  # Shape: [sequence_length, vocab_size]

        # Apply softmax to each token’s logits
        normalized_logits = [softmax_fn(torch.from_numpy(token_logits)) for token_logits in logits_array]

        # Analyze logits using the unified function
        result = analyze_logits(
            logit_tensor_sequence=normalized_logits,
            input_token_ids=tokenized_inputs[sample_idx],
            tokenizer_fn=tokenizer,
            skip_first_token=skip_first_token
        )

        max_logit_predictions.append(result["max_cases"])
        min_logit_predictions.append(result["min_cases"])
        actual_logit_scores.append(result["actual_logits"])

        logging.info(f"Processed sample {sample_idx}")
        print(f"Processed sample {sample_idx}")

    return max_logit_predictions, min_logit_predictions, actual_logit_scores

In [22]:
input_ids_list = tokenizer.batch_encode_plus(df_dataset[params['dataset']['content_column']].tolist())
input_ids_list = [torch.tensor(  input_ids, dtype = torch.int) for input_ids in input_ids_list.input_ids]

In [23]:
max_logit_token_prompt, min_logit_token_prompt, actual_logit_token_prompt = process_logit_batches(
    tokenizer=tokenizer , tokenized_inputs=input_ids_list, 
    num_samples = len(df_dataset)
) #<---WARNING TIME Consuming

Processed sample 0
Processed sample 1
Processed sample 2
Processed sample 3
Processed sample 4
Processed sample 5
Processed sample 6
Processed sample 7
Processed sample 8
Processed sample 9
Processed sample 10
Processed sample 11
Processed sample 12
Processed sample 13
Processed sample 14
Processed sample 15
Processed sample 16
Processed sample 17
Processed sample 18
Processed sample 19
Processed sample 20
Processed sample 21
Processed sample 22
Processed sample 23
Processed sample 24
Processed sample 25
Processed sample 26
Processed sample 27
Processed sample 28
Processed sample 29
Processed sample 30
Processed sample 31
Processed sample 32
Processed sample 33
Processed sample 34
Processed sample 35
Processed sample 36
Processed sample 37
Processed sample 38
Processed sample 39
Processed sample 40
Processed sample 41
Processed sample 42
Processed sample 43
Processed sample 44
Processed sample 45
Processed sample 46
Processed sample 47
Processed sample 48
Processed sample 49
Processed sample 50
Processed sample 51
Processed sample 52
Processed sample 53
Processed sample 54
Processed sample 55
Processed sample 56
Processed sample 57
Processed sample 58
Processed sample 59
Processed sample 60
Processed sample 61
Processed sample 62
Processed sample 63
Processed sample 64
Processed sample 65
Processed sample 66
Processed sample 67
Processed sample 68
Processed sample 69
Processed sample 70
Processed sample 71
Processed sample 72
Processed sample 73
Processed sample 74
Processed sample 75
Processed sample 76
Processed sample 77
Processed sample 78
Processed sample 79
Processed sample 80
Processed sample 81
Processed sample 82
Processed sample 83
Processed sample 84
Processed sample 85
Processed sample 86
Processed sample 87
Processed sample 88
Processed sample 89
Processed sample 90
Processed sample 91
Processed sample 92
Processed sample 93
Processed sample 94
Processed sample 95
Processed sample 96
Processed sample 97
Processed sample 98
Processed sample 99
Processed sample 100
Processed sample 101
Processed sample 102
Processed sample 103
Processed sample 104
Processed sample 105
Processed sample 106
Processed sample 107
Processed sample 108
Processed sample 109
Processed sample 110
Processed sample 111
Processed sample 112
Processed sample 113
Processed sample 114
Processed sample 115
Processed sample 116
Processed sample 117
Processed sample 118
Processed sample 119
Processed sample 120
Processed sample 121
Processed sample 122
Processed sample 123
Processed sample 124
Processed sample 125
Processed sample 126
Processed sample 127
Processed sample 128
Processed sample 129
Processed sample 130
Processed sample 131
Processed sample 132
Processed sample 133
Processed sample 134
Processed sample 135
Processed sample 136
Processed sample 137
Processed sample 138
Processed sample 139
Processed sample 140
Processed sample 141
Processed sample 142
Processed sample 143
Processed sample 144
Processed sample 145
Processed sample 146
Processed sample 147
Processed sample 148
Processed sample 149
Processed sample 150
Processed sample 151
Processed sample 152
Processed sample 153
Processed sample 154
Processed sample 155
Processed sample 156
Processed sample 157
Processed sample 158
Processed sample 159
Processed sample 160
Processed sample 161
Processed sample 162
Processed sample 163
Processed sample 164
Processed sample 165
Processed sample 166
Processed sample 167
Processed sample 168
Processed sample 169
Processed sample 170
Processed sample 171
Processed sample 172
Processed sample 173
Processed sample 174
Processed sample 175
Processed sample 176
Processed sample 177
Processed sample 178
Processed sample 179
Processed sample 180
Processed sample 181
Processed sample 182
Processed sample 183
Processed sample 184
Processed sample 185
Processed sample 186
Processed sample 187
Processed sample 188
Processed sample 189
Processed sample 190
Processed sample 191
Processed sample 192
Processed sample 193
Processed sample 194
Processed sample 195
Processed sample 196
Processed sample 197
Processed sample 198
Processed sample 199
Processed sample 200
Processed sample 201
Processed sample 202
Processed sample 203
Processed sample 204
Processed sample 205
Processed sample 206
Processed sample 207
Processed sample 208
Processed sample 209
Processed sample 210
Processed sample 211
Processed sample 212
Processed sample 213
Processed sample 214
Processed sample 215
Processed sample 216
Processed sample 217
Processed sample 218
Processed sample 219
Processed sample 220
Processed sample 221
Processed sample 222
Processed sample 223
Processed sample 224
Processed sample 225
Processed sample 226
Processed sample 227
Processed sample 228
Processed sample 229
Processed sample 230
Processed sample 231
Processed sample 232
Processed sample 233
Processed sample 234
Processed sample 235
Processed sample 236
Processed sample 237
Processed sample 238
Processed sample 239
Processed sample 240
Processed sample 241
Processed sample 242
Processed sample 243
Processed sample 244
Processed sample 245
Processed sample 246
Processed sample 247
Processed sample 248
Processed sample 249
Processed sample 250
Processed sample 251
Processed sample 252
Processed sample 253
Processed sample 254
Processed sample 255
Processed sample 256
Processed sample 257
Processed sample 258
Processed sample 259
Processed sample 260
Processed sample 261
Processed sample 262
Processed sample 263
Processed sample 264
Processed sample 265
Processed sample 266
Processed sample 267
Processed sample 268
Processed sample 269
Processed sample 270
Processed sample 271
Processed sample 272
Processed sample 273
Processed sample 274
Processed sample 275
Processed sample 276
Processed sample 277
Processed sample 278
Processed sample 279
Processed sample 280
Processed sample 281
Processed sample 282
Processed sample 283
Processed sample 284
Processed sample 285
Processed sample 286
Processed sample 287
Processed sample 288
Processed sample 289
Processed sample 290
Processed sample 291
Processed sample 292
Processed sample 293
Processed sample 294
Processed sample 295
Processed sample 296
Processed sample 297
Processed sample 298
Processed sample 299
Processed sample 300
Processed sample 301
Processed sample 302
Processed sample 303
Processed sample 304
Processed sample 305
Processed sample 306
Processed sample 307
Processed sample 308
Processed sample 309
Processed sample 310
Processed sample 311
Processed sample 312
Processed sample 313
Processed sample 314
Processed sample 315
Processed sample 316
Processed sample 317
Processed sample 318
Processed sample 319
Processed sample 320
Processed sample 321
Processed sample 322
Processed sample 323
Processed sample 324
Processed sample 325
Processed sample 326
Processed sample 327
Processed sample 328
Processed sample 329
Processed sample 330
Processed sample 331
Processed sample 332
Processed sample 333
Processed sample 334
Processed sample 335
Processed sample 336
Processed sample 337
Processed sample 338
Processed sample 339
Processed sample 340
Processed sample 341
Processed sample 342
Processed sample 343
Processed sample 344
Processed sample 345
Processed sample 346
Processed sample 347
Processed sample 348
Processed sample 349
Processed sample 350
Processed sample 351
Processed sample 352
Processed sample 353
Processed sample 354
Processed sample 355
Processed sample 356
Processed sample 357
Processed sample 358
Processed sample 359
Processed sample 360
Processed sample 361
Processed sample 362
Processed sample 363
Processed sample 364
Processed sample 365
Processed sample 366
Processed sample 367
Processed sample 368
Processed sample 369
Processed sample 370
Processed sample 371
Processed sample 372
Processed sample 373
Processed sample 374
Processed sample 375
Processed sample 376
Processed sample 377
Processed sample 378
Processed sample 379
Processed sample 380
Processed sample 381
Processed sample 382
Processed sample 383
Processed sample 384
Processed sample 385
Processed sample 386
Processed sample 387
Processed sample 388
Processed sample 389
Processed sample 390
Processed sample 391
Processed sample 392
Processed sample 393
Processed sample 394
Processed sample 395
Processed sample 396
Processed sample 397
Processed sample 398
Processed sample 399
Processed sample 400
Processed sample 401
Processed sample 402
Processed sample 403
Processed sample 404
Processed sample 405
Processed sample 406
Processed sample 407
Processed sample 408
Processed sample 409
Processed sample 410
Processed sample 411
Processed sample 412
Processed sample 413
Processed sample 414
Processed sample 415
Processed sample 416
Processed sample 417
Processed sample 418
Processed sample 419
Processed sample 420
Processed sample 421
Processed sample 422
Processed sample 423
Processed sample 424
Processed sample 425
Processed sample 426
Processed sample 427
Processed sample 428
Processed sample 429
Processed sample 430
Processed sample 431
Processed sample 432
Processed sample 433
Processed sample 434
Processed sample 435
Processed sample 436
Processed sample 437
Processed sample 438
Processed sample 439
Processed sample 440
Processed sample 441
Processed sample 442
Processed sample 443
Processed sample 444
Processed sample 445
Processed sample 446
Processed sample 447
Processed sample 448
Processed sample 449
Processed sample 450
Processed sample 451
Processed sample 452
Processed sample 453
Processed sample 454
Processed sample 455
Processed sample 456
Processed sample 457
Processed sample 458
Processed sample 459
Processed sample 460
Processed sample 461
Processed sample 462
Processed sample 463
Processed sample 464
Processed sample 465
Processed sample 466
Processed sample 467
Processed sample 468
Processed sample 469
Processed sample 470
Processed sample 471
Processed sample 472
Processed sample 473
Processed sample 474
Processed sample 475
Processed sample 476
Processed sample 477
Processed sample 478
Processed sample 479
Processed sample 480
Processed sample 481
Processed sample 482
Processed sample 483
Processed sample 484
Processed sample 485
Processed sample 486
Processed sample 487
Processed sample 488
Processed sample 489
Processed sample 490
Processed sample 491
Processed sample 492
Processed sample 493
Processed sample 494
Processed sample 495
Processed sample 496
Processed sample 497
Processed sample 498
Processed sample 499
Processed sample 500
Processed sample 501
Processed sample 502
Processed sample 503
Processed sample 504
Processed sample 505
Processed sample 506
Processed sample 507
Processed sample 508
Processed sample 509
Processed sample 510
Processed sample 511
Processed sample 512
Processed sample 513
Processed sample 514
Processed sample 515
Processed sample 516
Processed sample 517
Processed sample 518
Processed sample 519
Processed sample 520
Processed sample 521
Processed sample 522
Processed sample 523
Processed sample 524
Processed sample 525
Processed sample 526
Processed sample 527
Processed sample 528
Processed sample 529
Processed sample 530
Processed sample 531
Processed sample 532
Processed sample 533
Processed sample 534
Processed sample 535
Processed sample 536
Processed sample 537
Processed sample 538
Processed sample 539
Processed sample 540
Processed sample 541
Processed sample 542
Processed sample 543
Processed sample 544
Processed sample 545
Processed sample 546
Processed sample 547
Processed sample 548
Processed sample 549
Processed sample 550
Processed sample 551
Processed sample 552
Processed sample 553
Processed sample 554
Processed sample 555
Processed sample 556
Processed sample 557
Processed sample 558
Processed sample 559
Processed sample 560
Processed sample 561
Processed sample 562
Processed sample 563
Processed sample 564
Processed sample 565
Processed sample 566
Processed sample 567
Processed sample 568
Processed sample 569
Processed sample 570
Processed sample 571
Processed sample 572
Processed sample 573
Processed sample 574
Processed sample 575
Processed sample 576
Processed sample 577
Processed sample 578
Processed sample 579
Processed sample 580
Processed sample 581
Processed sample 582
Processed sample 583
Processed sample 584
Processed sample 585
Processed sample 586
Processed sample 587
Processed sample 588
Processed sample 589
Processed sample 590
Processed sample 591
Processed sample 592
Processed sample 593
Processed sample 594
Processed sample 595
Processed sample 596
Processed sample 597
Processed sample 598
Processed sample 599
Processed sample 600
Processed sample 601
Processed sample 602
Processed sample 603
Processed sample 604
Processed sample 605
Processed sample 606
Processed sample 607
Processed sample 608
Processed sample 609
Processed sample 610
Processed sample 611
Processed sample 612
Processed sample 613
Processed sample 614
Processed sample 615
Processed sample 616
Processed sample 617
Processed sample 618
Processed sample 619
Processed sample 620
Processed sample 621
Processed sample 622
Processed sample 623
Processed sample 624
Processed sample 625
Processed sample 626
Processed sample 627
Processed sample 628
Processed sample 629
Processed sample 630
Processed sample 631
Processed sample 632
Processed sample 633
Processed sample 634
Processed sample 635
Processed sample 636
Processed sample 637
Processed sample 638
Processed sample 639
Processed sample 640
Processed sample 641
Processed sample 642
Processed sample 643
Processed sample 644
Processed sample 645
Processed sample 646
Processed sample 647
Processed sample 648
Processed sample 649
Processed sample 650
Processed sample 651
Processed sample 652
Processed sample 653
Processed sample 654
Processed sample 655
Processed sample 656
Processed sample 657
Processed sample 658
Processed sample 659
Processed sample 660
Processed sample 661
Processed sample 662
Processed sample 663
Processed sample 664
Processed sample 665
Processed sample 666
Processed sample 667
Processed sample 668
Processed sample 669
Processed sample 670
Processed sample 671
Processed sample 672
Processed sample 673
Processed sample 674
Processed sample 675
Processed sample 676
Processed sample 677
Processed sample 678
Processed sample 679
Processed sample 680
Processed sample 681
Processed sample 682
Processed sample 683
Processed sample 684
Processed sample 685
Processed sample 686
Processed sample 687
Processed sample 688
Processed sample 689
Processed sample 690
Processed sample 691
Processed sample 692
Processed sample 693
Processed sample 694
Processed sample 695
Processed sample 696
Processed sample 697
Processed sample 698
Processed sample 699
Processed sample 700
Processed sample 701
Processed sample 702
Processed sample 703
Processed sample 704
Processed sample 705
Processed sample 706
Processed sample 707
Processed sample 708
Processed sample 709
Processed sample 710
Processed sample 711
Processed sample 712
Processed sample 713
Processed sample 714
Processed sample 715
Processed sample 716
Processed sample 717
Processed sample 718
Processed sample 719
Processed sample 720
Processed sample 721
Processed sample 722
Processed sample 723
Processed sample 724
Processed sample 725
Processed sample 726
Processed sample 727
Processed sample 728
Processed sample 729
Processed sample 730
Processed sample 731
Processed sample 732
Processed sample 733
Processed sample 734
Processed sample 735
Processed sample 736
Processed sample 737
Processed sample 738
Processed sample 739
Processed sample 740
Processed sample 741
Processed sample 742
Processed sample 743
Processed sample 744
Processed sample 745
Processed sample 746
Processed sample 747
Processed sample 748
Processed sample 749
Processed sample 750
Processed sample 751
Processed sample 752
Processed sample 753
Processed sample 754
Processed sample 755
Processed sample 756
Processed sample 757
Processed sample 758
Processed sample 759
Processed sample 760
Processed sample 761
Processed sample 762
Processed sample 763
Processed sample 764
Processed sample 765
Processed sample 766
Processed sample 767
Processed sample 768
Processed sample 769
Processed sample 770
Processed sample 771
Processed sample 772
Processed sample 773
Processed sample 774
Processed sample 775
Processed sample 776
Processed sample 777
Processed sample 778
Processed sample 779
Processed sample 780
Processed sample 781
Processed sample 782
Processed sample 783
Processed sample 784
Processed sample 785
Processed sample 786
Processed sample 787
Processed sample 788
Processed sample 789
Processed sample 790
Processed sample 791
Processed sample 792
Processed sample 793
Processed sample 794
Processed sample 795
Processed sample 796
Processed sample 797
Processed sample 798
Processed sample 799
Processed sample 800
Processed sample 801
Processed sample 802
Processed sample 803
Processed sample 804
Processed sample 805
Processed sample 806
Processed sample 807
Processed sample 808
Processed sample 809
Processed sample 810
Processed sample 811
Processed sample 812
Processed sample 813
Processed sample 814
Processed sample 815
Processed sample 816
Processed sample 817
Processed sample 818
Processed sample 819
Processed sample 820
Processed sample 821
Processed sample 822
Processed sample 823
Processed sample 824
Processed sample 825
Processed sample 826
Processed sample 827
Processed sample 828
Processed sample 829
Processed sample 830
Processed sample 831
Processed sample 832
Processed sample 833
Processed sample 834
Processed sample 835
Processed sample 836
Processed sample 837
Processed sample 838
Processed sample 839
Processed sample 840
Processed sample 841
Processed sample 842
Processed sample 843
Processed sample 844
Processed sample 845
Processed sample 846
Processed sample 847
Processed sample 848
Processed sample 849
Processed sample 850
Processed sample 851
Processed sample 852
Processed sample 853
Processed sample 854
Processed sample 855
Processed sample 856
Processed sample 857
Processed sample 858
Processed sample 859
Processed sample 860
Processed sample 861
Processed sample 862
Processed sample 863
Processed sample 864
Processed sample 865
Processed sample 866
Processed sample 867
Processed sample 868
Processed sample 869
Processed sample 870
Processed sample 871
Processed sample 872
Processed sample 873
Processed sample 874
Processed sample 875
Processed sample 876
Processed sample 877
Processed sample 878
Processed sample 879
Processed sample 880
Processed sample 881
Processed sample 882
Processed sample 883
Processed sample 884
Processed sample 885
Processed sample 886
Processed sample 887
Processed sample 888
Processed sample 889
Processed sample 890
Processed sample 891
Processed sample 892
Processed sample 893
Processed sample 894
Processed sample 895
Processed sample 896
Processed sample 897
Processed sample 898
Processed sample 899
Processed sample 900
Processed sample 901
Processed sample 902
Processed sample 903
Processed sample 904
Processed sample 905
Processed sample 906
Processed sample 907
Processed sample 908
Processed sample 909
Processed sample 910
Processed sample 911
Processed sample 912
Processed sample 913
Processed sample 914
Processed sample 915
Processed sample 916
Processed sample 917
Processed sample 918
Processed sample 919
Processed sample 920
Processed sample 921
Processed sample 922
Processed sample 923
Processed sample 924
Processed sample 925
Processed sample 926
Processed sample 927
Processed sample 928
Processed sample 929
Processed sample 930
Processed sample 931
Processed sample 932
Processed sample 933
Processed sample 934
Processed sample 935
Processed sample 936
Processed sample 937
Processed sample 938
Processed sample 939
Processed sample 940
Processed sample 941
Processed sample 942
Processed sample 943
Processed sample 944
Processed sample 945
Processed sample 946
Processed sample 947
Processed sample 948
Processed sample 949
Processed sample 950
Processed sample 951
Processed sample 952
Processed sample 953
Processed sample 954
Processed sample 955
Processed sample 956

#### Saving results

In [24]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [25]:
dataframe_to_save = df_dataset.copy()
dataframe_to_save['max_prob'] = max_logit_token_prompt
dataframe_to_save['min_prob'] = min_logit_token_prompt
dataframe_to_save['actual_prob'] = actual_logit_token_prompt
dataframe_to_save.shape

(1500, 33)

In [26]:
output_dir = f"{params['output_path']}/{params['dataset']['current']}/{params['current_model']}_q_{params['quantization']}"
create_folder(output_dir)
dataframe_to_save.to_json(f"{output_dir}/raw_logits.json", index=False)

#### Loss Retrieval

In [27]:
def batching_loss( size = dataframe_to_save.shape[0] ):
    output_dir = f"{params['callbacks_path']}/{params['dataset']['current']}/{params['current_model']}_q_{params['quantization']}"
    output_loss = []
    for current_batch in range(size):
        out = np.load(f"{output_dir}/_loss_batch[{current_batch}].npy")
        output_loss.append( out.item() ) #.item() for numpy library
        logging.info(current_batch)
    return output_loss

In [28]:
output_loss = batching_loss() #[WAENING!] Takes Time

In [29]:
output_loss

[0.4817667007446289,
 1.2113902568817139,
 1.3814879655838013,
 0.48720982670783997,
 1.1836971044540405,
 0.9220165610313416,
 1.0162023305892944,
 0.9585427045822144,
 2.3622360229492188,
 1.4342334270477295,
 1.7954044342041016,
 1.1472768783569336,
 2.301631212234497,
 3.1858749389648438,
 0.9545468091964722,
 1.8392764329910278,
 1.280494213104248,
 1.1617343425750732,
 0.2592431902885437,
 0.6597101092338562,
 1.9887151718139648,
 1.833314061164856,
 1.473940372467041,
 1.7954044342041016,
 0.5083361864089966,
 2.794299364089966,
 1.626961350440979,
 0.9804427623748779,
 1.434414267539978,
 0.30446356534957886,
 0.6057441234588623,
 1.3440114259719849,
 1.1693793535232544,
 1.122738003730774,
 0.8383280634880066,
 0.878592848777771,
 0.6235223412513733,
 1.8597307205200195,
 1.84883451461792,
 0.9256730079650879,
 1.0020115375518799,
 0.7943770289421082,
 0.7912768721580505,
 1.579355239868164,
 1.360980749130249,
 0.9012847542762756,
 1.9246673583984375,
 2.067991018295288,
 0.902030348777771,
 2.6375465393066406,
 1.963036060333252,
 2.3206281661987305,
 1.8768177032470703,
 2.4832236766815186,
 0.20947784185409546,
 0.9356502890586853,
 1.2218188047409058,
 1.006956696510315,
 0.7042785286903381,
 0.8993372321128845,
 0.9803905487060547,
 0.822062611579895,
 1.8648968935012817,
 0.9918232560157776,
 2.4815938472747803,
 1.1111327409744263,
 2.1299901008605957,
 0.813703179359436,
 1.1920180320739746,
 1.1867927312850952,
 1.4535430669784546,
 1.4695327281951904,
 1.992942452430725,
 1.1845951080322266,
 1.9272578954696655,
 0.7160719633102417,
 1.785302996635437,
 1.1494804620742798,
 0.46964362263679504,
 1.2821862697601318,
 0.7375739812850952,
 1.8316798210144043,
 1.2513551712036133,
 0.9263641238212585,
 2.08941650390625,
 0.8212751150131226,
 1.1696717739105225,
 1.1275500059127808,
 1.623799443244934,
 0.6729176640510559,
 1.7581907510757446,
 1.1121370792388916,
 0.8543860912322998,
 0.9915919899940491,
 1.2067759037017822,
 1.0107147693634033,
 1.2495290040969849,
 0.6317843794822693,
 0.8918946385383606,
 0.9585427045822144,
 0.8761005401611328,
 0.8448126316070557,
 2.532583713531494,
 1.5154701471328735,
 1.548039436340332,
 1.338098406791687,
 1.8688533306121826,
 0.5787699222564697,
 1.4514096975326538,
 1.4873987436294556,
 0.8430006504058838,
 0.680271565914154,
 1.2717159986495972,
 0.14196042716503143,
 0.7843804955482483,
 0.8808174729347229,
 1.5189813375473022,
 1.0309041738510132,
 0.875093400478363,
 1.5991538763046265,
 0.7116079926490784,
 0.5804715156555176,
 2.5602569580078125,
 1.698382019996643,
 1.7063286304473877,
 0.895248293876648,
 1.590169072151184,
 0.6912826299667358,
 0.9825008511543274,
 1.4112548828125,
 1.2200669050216675,
 0.6806207895278931,
 1.068200707435608,
 1.1213709115982056,
 0.23704348504543304,
 0.7621430158615112,
 0.890649676322937,
 1.5921287536621094,
 1.085374355316162,
 1.3169482946395874,
 1.9019227027893066,
 1.8853352069854736,
 1.2126240730285645,
 0.8546184301376343,
 1.1284533739089966,
 1.4406920671463013,
 1.223284363746643,
 1.592703104019165,
 0.8566376566886902,
 2.497114896774292,
 0.890649676322937,
 1.0017368793487549,
 0.76917564868927,
 0.8618464469909668,
 0.9905130863189697,
 0.9919689893722534,
 2.721208095550537,
 1.7608953714370728,
 1.3509148359298706,
 0.6557458639144897,
 1.319122552871704,
 1.1900577545166016,
 1.0424647331237793,
 0.9911516308784485,
 1.2188458442687988,
 1.1281602382659912,
 1.3935904502868652,
 2.2746901512145996,
 1.3266018629074097,
 0.7807086110115051,
 1.1970328092575073,
 2.640843629837036,
 1.5582741498947144,
 0.9273916482925415,
 1.1784547567367554,
 1.462767243385315,
 1.162632942199707,
 0.7583115100860596,
 1.018101453781128,
 0.9437320232391357,
 0.7958884239196777,
 2.6739094257354736,
 1.3467350006103516,
 1.043168306350708,
 2.128472089767456,
 2.6302943229675293,
 0.9856263399124146,
 1.2310787439346313,
 3.0561156272888184,
 0.7468639612197876,
 0.9726210236549377,
 1.0794072151184082,
 1.1678849458694458,
 1.4539551734924316,
 1.8285290002822876,
 3.3665919303894043,
 1.8185569047927856,
 1.4365028142929077,
 2.5308289527893066,
 0.8368416428565979,
 0.9787895083427429,
 1.0260581970214844,
 2.3718104362487793,
 1.689663290977478,
 1.2586815357208252,
 0.8106363415718079,
 1.2142653465270996,
 1.111454963684082,
 1.259339451789856,
 0.7125226855278015,
 1.1121370792388916,
 1.7080646753311157,
 1.4794994592666626,
 0.7101153135299683,
 1.1789546012878418,
 1.1875998973846436,
 2.356914520263672,
 2.2789201736450195,
 1.0665745735168457,
 2.841217517852783,
 1.2389172315597534,
 0.8713146448135376,
 0.796857476234436,
 1.1254993677139282,
 0.9727320075035095,
 1.3270533084869385,
 0.9595617055892944,
 0.6129717826843262,
 0.9010838866233826,
 0.8466401100158691,
 1.791866660118103,
 1.606524109840393,
 0.6810696721076965,
 0.6416525840759277,
 0.569799542427063,
 1.3266814947128296,
 0.5073734521865845,
 1.709427833557129,
 0.6972543001174927,
 1.9464538097381592,
 1.0235530138015747,
 1.5850067138671875,
 1.7012909650802612,
 1.494539499282837,
 0.8899224996566772,
 0.9752921462059021,
 0.8279467225074768,
 0.8385610580444336,
 1.0590522289276123,
 1.152100920677185,
 1.0123589038848877,
 3.010128974914551,
 1.029770016670227,
 1.4378358125686646,
 2.1593306064605713,
 1.5581036806106567,
 1.2704541683197021,
 0.6261968016624451,
 1.1782052516937256,
 0.9574830532073975,
 1.689468502998352,
 2.2006630897521973,
 0.8761005401611328,
 1.7663228511810303,
 1.7087870836257935,
 0.9209425449371338,
 0.9510973691940308,
 0.9440140724182129,
 1.0010716915130615,
 0.8861508965492249,
 0.9780339598655701,
 2.1556315422058105,
 0.7182378172874451,
 2.057290554046631,
 1.9991240501403809,
 0.8642908334732056,
 2.392754077911377,
 1.8242998123168945,
 1.1253421306610107,
 0.9809374213218689,
 0.9084113836288452,
 1.014351725578308,
 2.0734357833862305,
 0.9774524569511414,
 0.8922518491744995,
 1.7413759231567383,
 1.6484248638153076,
 0.6843175292015076,
 1.9779307842254639,
 1.1049067974090576,
 1.9955713748931885,
 0.7465142011642456,
 3.0390148162841797,
 0.9940873980522156,
 2.3965539932250977,
 0.676872193813324,
 0.6978287100791931,
 0.8730522990226746,
 1.7473012208938599,
 1.5542874336242676,
 1.0371159315109253,
 1.1303502321243286,
 1.360947847366333,
 0.7798365354537964,
 1.4224634170532227,
 0.8645566701889038,
 1.4801758527755737,
 0.9574830532073975,
 1.1748446226119995,
 1.6389328241348267,
 2.3631744384765625,
 2.049314260482788,
 0.8488137722015381,
 1.2811224460601807,
 1.3812131881713867,
 1.3025552034378052,
 0.9622217416763306,
 0.8761005401611328,
 1.0711079835891724,
 1.6754765510559082,
 0.8728944063186646,
 0.9271615147590637,
 2.674752950668335,
 1.1457213163375854,
 1.2123925685882568,
 0.946993350982666,
 1.6187442541122437,
 1.3927940130233765,
 1.3323287963867188,
 1.2311338186264038,
 1.6075637340545654,
 1.9801669120788574,
 1.4130877256393433,
 1.1538958549499512,
 0.7142546772956848,
 0.796857476234436,
 0.9619653224945068,
 2.598447322845459,
 0.9753202199935913,
 1.610512137413025,
 1.0296478271484375,
 1.6390323638916016,
 0.6810696721076965,
 1.1402854919433594,
 1.0178065299987793,
 1.1722996234893799,
 0.6450498700141907,
 0.8757631778717041,
 1.6953767538070679,
 0.856344997882843,
 1.2332367897033691,
 0.874544084072113,
 1.1884793043136597,
 1.1907979249954224,
 1.6323659420013428,
 2.788499593734741,
 0.5898919105529785,
 1.6481163501739502,
 1.137328028678894,
 1.894854187965393,
 2.489490032196045,
 1.8774522542953491,
 1.4436380863189697,
 0.9209425449371338,
 0.8031057119369507,
 2.3649673461914062,
 1.8600884675979614,
 1.3875863552093506,
 1.4887034893035889,
 1.3156708478927612,
 0.7827228307723999,
 0.5292403697967529,
 1.8079913854599,
 2.1789612770080566,
 0.9321980476379395,
 1.1121370792388916,
 0.9919689893722534,
 1.8205070495605469,
 0.9792510271072388,
 0.8928667306900024,
 1.3129205703735352,
 0.8510081768035889,
 0.6282912492752075,
 0.7940167784690857,
 0.8007479310035706,
 0.890649676322937,
 1.113021731376648,
 0.9061650633811951,
 1.1167035102844238,
 1.2416352033615112,
 1.6582282781600952,
 1.1329195499420166,
 0.38405701518058777,
 1.2991607189178467,
 0.8059272766113281,
 1.530978798866272,
 0.5763617157936096,
 1.6294993162155151,
 1.04037344455719,
 1.9474695920944214,
 2.357421398162842,
 1.6883882284164429,
 0.7297870516777039,
 1.4987369775772095,
 0.9704299569129944,
 0.4851783215999603,
 1.2939507961273193,
 2.4246315956115723,
 1.7216129302978516,
 1.5658982992172241,
 1.16681706905365,
 1.3427129983901978,
 0.9051355719566345,
 1.4181731939315796,
 2.0566258430480957,
 1.3648924827575684,
 1.8428752422332764,
 0.6232600212097168,
 1.1386090517044067,
 1.2064601182937622,
 1.201072096824646,
 0.7531976699829102,
 0.577437162399292,
 2.92161226272583,
 1.8222041130065918,
 0.9350253343582153,
 0.8631328344345093,
 1.5367858409881592,
 0.9313657283782959,
 1.0907937288284302,
 1.0149991512298584,
 0.6891003847122192,
 0.7173347473144531,
 1.814996361732483,
 0.7239673733711243,
 0.5320971012115479,
 1.2571696043014526,
 1.3613557815551758,
 0.5962156057357788,
 1.4657412767410278,
 1.282239556312561,
 1.1144967079162598,
 1.9397071599960327,
 2.643645763397217,
 0.9821570515632629,
 0.5401452779769897,
 2.236905097961426,
 0.9055389761924744,
 0.43072599172592163,
 1.2274997234344482,
 2.224601984024048,
 0.23586462438106537,
 1.4514912366867065,
 1.1998151540756226,
 2.2205190658569336,
 2.5357184410095215,
 1.192143201828003,
 1.207193374633789,
 1.3046245574951172,
 1.815669059753418,
 1.0280425548553467,
 1.6322145462036133,
 1.3962990045547485,
 1.544051170349121,
 1.2109277248382568,
 1.4745444059371948,
 1.221163034439087,
 1.6154553890228271,
 1.6153564453125,
 1.4530059099197388,
 1.0669255256652832,
 1.4943848848342896,
 0.796857476234436,
 1.3167672157287598,
 0.9868438243865967,
 1.295457124710083,
 0.5898919105529785,
 1.052016258239746,
 1.5366570949554443,
 1.2532587051391602,
 1.6761813163757324,
 1.0260581970214844,
 1.612514853477478,
 0.24523019790649414,
 2.834141492843628,
 0.8430006504058838,
 2.0785229206085205,
 1.4243241548538208,
 0.32006600499153137,
 0.8149736523628235,
 1.1860743761062622,
 1.589514970779419,
 1.3341302871704102,
 1.4216609001159668,
 1.216921329498291,
 2.4645111560821533,
 1.6327766180038452,
 0.9087047576904297,
 1.3007688522338867,
 1.0424264669418335,
 2.386087656021118,
 1.116786003112793,
 2.053957462310791,
 0.9545468091964722,
 1.0092982053756714,
 1.275754451751709,
 0.616710364818573,
 1.9818180799484253,
 1.997948169708252,
 1.1940855979919434,
 1.1541858911514282,
 0.9734068512916565,
 1.294981598854065,
 0.7514134645462036,
 0.8870671391487122,
 1.4157434701919556,
 0.730359673500061,
 0.8653507828712463,
 2.932396173477173,
 1.471649169921875,
 2.661381244659424,
 0.7179148197174072,
 1.6196048259735107,
 0.5173410773277283,
 2.0218849182128906,
 1.9347138404846191,
 0.646217942237854,
 1.2424795627593994,
 1.3521865606307983,
 1.0807864665985107,
 1.107418417930603,
 1.7899121046066284,
 0.8666830658912659,
 1.7402194738388062,
 1.072386384010315,
 1.7240803241729736,
 0.8902209997177124,
 1.1148841381072998,
 1.1946967840194702,
 0.8738685846328735,
 1.728606104850769,
 2.80405855178833,
 0.5898919105529785,
 1.1401649713516235,
 0.7220783233642578,
 1.755873203277588,
 1.142410397529602,
 0.47180983424186707,
 0.5682662129402161,
 1.0987123250961304,
 1.0300929546356201,
 1.3068797588348389,
 1.689663290977478,
 1.278062105178833,
 1.6278384923934937,
 0.680271565914154,
 0.8700758814811707,
 1.548039436340332,
 2.3087475299835205,
 1.4048614501953125,
 1.2366195917129517,
 0.8149736523628235,
 0.9483403563499451,
 1.2469847202301025,
 1.6440751552581787,
 1.1791619062423706,
 2.630768060684204,
 1.4162808656692505,
 3.298550605773926,
 1.2234480381011963,
 1.0225729942321777,
 2.3206281661987305,
 1.3763935565948486,
 0.9919689893722534,
 1.043932557106018,
 1.5391194820404053,
 0.7836403846740723,
 1.2891168594360352,
 1.9293850660324097,
 1.412165641784668,
 1.760457158088684,
 2.2935683727264404,
 1.190911889076233,
 0.7602032423019409,
 0.9162977337837219,
 1.1907049417495728,
 1.6756706237792969,
 2.5988378524780273,
 0.6527636647224426,
 1.5789573192596436,
 0.47742199897766113,
 0.7202356457710266,
 0.6177945733070374,
 0.7295228242874146,
 0.8918802738189697,
 1.299553394317627,
 0.8391941785812378,
 0.59104323387146,
 0.9609576463699341,
 1.5788564682006836,
 2.3276987075805664,
 0.16851025819778442,
 0.9301161170005798,
 0.8455492258071899,
 1.2498300075531006,
 1.7228389978408813,
 1.493216633796692,
 0.9633978009223938,
 0.8594955205917358,
 1.3976861238479614,
 0.7947189211845398,
 1.0580413341522217,
 0.6379430890083313,
 0.6086077094078064,
 2.1717545986175537,
 1.6045292615890503,
 1.3532536029815674,
 0.7999671697616577,
 1.8608272075653076,
 1.2058007717132568,
 0.6464148759841919,
 1.1852470636367798,
 0.9574830532073975,
 0.577437162399292,
 2.073347806930542,
 2.1211655139923096,
 1.3992664813995361,
 0.8069637417793274,
 2.089940071105957,
 2.7099897861480713,
 1.2716528177261353,
 1.6116780042648315,
 1.5380245447158813,
 0.6215311288833618,
 1.542883276939392,
 1.8242191076278687,
 1.8735398054122925,
 2.176831007003784,
 1.0983878374099731,
 0.42051300406455994,
 0.9960440993309021,
 1.152480125427246,
 0.6768996119499207,
 0.7833303809165955,
 1.5521761178970337,
 1.2821232080459595,
 1.7036818265914917,
 0.9600871205329895,
 0.41830742359161377,
 0.5169664621353149,
 1.2372498512268066,
 1.1538441181182861,
 0.9956464171409607,
 1.9454752206802368,
 1.294757604598999,
 1.2413231134414673,
 1.1457213163375854,
 1.043102502822876,
 1.1303445100784302,
 0.6904333233833313,
 1.4925799369812012,
 1.1569522619247437,
 0.6698389053344727,
 1.5692870616912842,
 0.9874903559684753,
 1.9914089441299438,
 1.0669947862625122,
 0.6549391746520996,
 2.4581122398376465,
 3.2256650924682617,
 0.8281319737434387,
 1.5110504627227783,
 1.3238283395767212,
 1.306606650352478,
 1.2597646713256836,
 2.1443963050842285,
 0.8107042908668518,
 0.7675788402557373,
 1.1561857461929321,
 1.3292794227600098,
 0.9574830532073975,
 2.260302782058716,
 0.8383280634880066,
 1.120093822479248,
 1.9144235849380493,
 1.060404896736145,
 2.99619460105896,
 1.4657412767410278,
 1.0356031656265259,
 1.2478604316711426,
 1.5995070934295654,
 1.0346144437789917,
 1.5149831771850586,
 0.7365847826004028,
 0.991929292678833,
 2.2047481536865234,
 0.7318066358566284,
 0.7968727946281433,
 1.2435860633850098,
 0.6822408437728882,
 0.97835373878479,
 0.8718339800834656,
 1.611304759979248,
 1.2844778299331665,
 1.4262632131576538,
 0.49039000272750854,
 2.2609455585479736,
 1.8873940706253052,
 0.7548621892929077,
 1.1354559659957886,
 0.4445152282714844,
 1.112511157989502,
 2.0718488693237305,
 1.0702729225158691,
 2.3371522426605225,
 0.5545637607574463,
 2.2267918586730957,
 0.9004945158958435,
 0.6939271688461304,
 2.640843629837036,
 0.8245682120323181,
 1.0210764408111572,
 1.14548659324646,
 1.4352933168411255,
 1.2098411321640015,
 1.4061970710754395,
 1.3022618293762207,
 0.8485783338546753,
 1.2062243223190308,
 1.4845662117004395,
 1.0587571859359741,
 1.9674487113952637,
 3.3735508918762207,
 1.911988377571106,
 0.8419284224510193,
 1.1030893325805664,
 2.673413038253784,
 0.8631169199943542,
 1.5683363676071167,
 1.9321211576461792,
 1.163959264755249,
 1.100881814956665,
 1.1251952648162842,
 1.84883451461792,
 1.3024744987487793,
 1.2617759704589844,
 0.4821588695049286,
 0.8364367485046387,
 0.6048949956893921,
 0.8543860912322998,
 1.9788038730621338,
 0.7999671697616577,
 1.1542249917984009,
 1.164000391960144,
 1.0625535249710083,
 1.753283977508545,
 0.8799624443054199,
 1.2923121452331543,
 1.4881935119628906,
 0.4852806627750397,
 0.8452510237693787,
 1.4606119394302368,
 1.2266521453857422,
 0.8632532358169556,
 2.761296510696411,
 1.5632681846618652,
 0.902154266834259,
 1.7111907005310059,
 0.9800167679786682,
 1.267464518547058,
 0.7226118445396423,
 1.8856836557388306,
 1.6525613069534302,
 1.4811428785324097,
 0.9350253343582153,
 0.9472638368606567,
 0.7697106599807739,
 0.6058859825134277,
 1.009276270866394,
 1.2875577211380005,
 2.030237913131714,
 1.2749139070510864,
 1.7002453804016113,
 1.4678972959518433,
 0.9245468974113464,
 1.7824102640151978,
 0.8728944063186646,
 0.6358134150505066,
 1.2758517265319824,
 0.8519997000694275,
 1.8856849670410156,
 1.043607234954834,
 2.195255994796753,
 0.8728944063186646,
 1.6084961891174316,
 0.6157198548316956,
 0.6848141551017761,
 1.7776398658752441,
 2.1558454036712646,
 1.8087691068649292,
 0.2402903437614441,
 0.8596740365028381,
 0.6283665299415588,
 0.8799624443054199,
 0.74196857213974,
 1.3026975393295288,
 2.5030176639556885,
 1.6115797758102417,
 0.9440503120422363,
 0.6129717826843262,
 1.529915690422058,
 0.8809863328933716,
 1.079845666885376,
 1.2275253534317017,
 1.3243016004562378,
 1.4484190940856934,
 0.787155032157898,
 0.8329158425331116,
 1.10584557056427,
 2.3662736415863037,
 1.5403114557266235,
 0.8637605905532837,
 0.7994599938392639,
 0.5451313257217407,
 1.1481928825378418,
 1.060815453529358,
 1.1731563806533813,
 1.4821234941482544,
 1.1792978048324585,
 0.9676990509033203,
 1.689468502998352,
 1.7019462585449219,
 1.3680862188339233,
 2.489490032196045,
 0.8780075311660767,
 1.2189921140670776,
 0.8543860912322998,
 2.092158317565918,
 2.4356391429901123,
 0.6516364216804504,
 1.012608528137207,
 0.6351917386054993,
 0.8784850835800171,
 1.4108645915985107,
 0.8014016151428223,
 1.7632390260696411,
 0.7048872113227844,
 1.037185549736023,
 0.8728944063186646,
 1.2204898595809937,
 2.232618570327759,
 1.180289387702942,
 1.1616469621658325,
 1.303059458732605,
 1.0275287628173828,
 0.8902196288108826,
 0.7950083017349243,
 0.8664349317550659,
 0.8543291687965393,
 0.9911516308784485,
 2.7320902347564697,
 0.9308915734291077,
 1.848541021347046,
 1.096326470375061,
 0.5241454839706421,
 1.799683690071106,
 1.5581036806106567,
 0.9547207355499268,
 1.3152596950531006,
 1.2678642272949219,
 1.6649258136749268,
 1.4499372243881226,
 3.4413371086120605,
 0.7689316272735596,
 0.794530987739563,
 1.090835452079773,
 0.753037691116333,
 0.9018538594245911,
 1.0275354385375977,
 1.1090741157531738,
 1.8065868616104126,
 2.5865509510040283,
 1.0926237106323242,
 0.7936238050460815,
 0.9297237992286682,
 0.9574830532073975,
 1.7337627410888672,
 2.3818576335906982,
 1.2080609798431396,
 1.5353642702102661,
 1.1253224611282349,
 0.7704422473907471,
 0.9628615379333496,
 1.4033088684082031,
 0.9998135566711426,
 1.0550117492675781,
 0.8543860912322998,
 0.5786725878715515,
 0.9821587204933167,
 0.9988560080528259,
 1.7485357522964478,
 2.6301679611206055,
 1.1907049417495728,
 0.8276636004447937,
 0.832573413848877,
 0.8902196288108826,
 0.7844454646110535,
 0.6622825264930725,
 1.4799443483352661,
 1.037185549736023,
 0.6968801021575928,
 1.4934033155441284,
 1.0022538900375366,
 0.7869517803192139,
 1.7800184488296509,
 0.8728944063186646,
 1.4451968669891357,
 1.1960099935531616,
 0.4916224479675293,
 1.0401890277862549,
 0.5913966298103333,
 1.2352122068405151,
 3.165985584259033,
 1.278201937675476,
 1.1458985805511475,
 1.231980800628662,
 0.6380324959754944,
 0.8097237944602966,
 0.9919689893722534,
 0.832573413848877,
 0.890649676322937,
 2.1063392162323,
 0.7204168438911438,
 0.7943770289421082,
 1.0210764408111572,
 1.7776046991348267,
 0.7754493355751038,
 2.1284849643707275,
 1.4906458854675293,
 0.890649676322937,
 0.8364367485046387,
 1.2556740045547485,
 1.1489074230194092,
 2.0735785961151123,
 1.0983878374099731,
 1.5077846050262451,
 0.8717765212059021,
 1.2260950803756714,
 0.7501341104507446,
 1.0744332075119019,
 1.4898786544799805,
 1.2813855409622192,
 1.1920180320739746,
 1.595799207687378,
 2.1063392162323,
 1.6964049339294434,
 1.0024054050445557,
 2.328723192214966,
 1.0703394412994385,
 0.9288391470909119,
 0.6379430890083313,
 0.9678892493247986,

In [30]:
dataframe_to_save['loss'] = output_loss
dataframe_to_save.head(5)

,id,commit_id,repo,path,file_name,fun_name,commit_message,code,url,language,...,s_end_line,s_end_column,s_code,category,input_lenght,input_ids,max_prob,min_prob,actual_prob,loss
0,278224,ebb5e0e3f5e0b02cad2b54144022084301588ac5,keras,keras/mixed_precision/loss_scale_optimizer_tes...,loss_scale_optimizer_test.py,testHyperParametersExposed,resolve line-too-long in mixed_precision,def testHyperParametersExposed(self):\n ...,https://github.com/keras-team/keras.git,Python,...,30,73,# LossScaleOptimizer and hyperpara...,Convention,535,"[822, 1243, 26322, 546, 11507, 1252, 4752, 298...","[(<PRE>, 0.7492900490760803), (module, 0.47944...","[(<s>, 6.321457571810407e-13), ($}, 1.21011436...","[(def, 0.0007611316395923495), (test, 0.019638...",0.481767
1,276644,84afc5193d38057e2e2badf9c889ea87d80d8fbf,keras,keras/tests/tracking_util_with_v1_optimizers_t...,tracking_util_with_v1_optimizers_test.py,__init__,Reformatting the codebase with black.\n\nPiper...,def __init__(self):\n super().__init__(...,https://github.com/keras-team/keras.git,Python,...,7,30,# pylint: disable=not-callable,Convention,61,"[822, 4770, 2344, 12035, 1311, 1125, 13, 4706,...","[(<PRE>, 0.7492942214012146), (module, 0.47944...","[(<s>, 6.322590020979568e-13), ($}, 1.21010909...","[(def, 0.0007611323380842805), (__, 0.00598202...",1.211390
2,24968,1a0a75e3fa896cf3c095e4146a54acef7223657e,PaddleOCR,ppstructure/pdf2word/pdf2word.py,pdf2word.py,predictAndSave,Add pdf2word exe\n\nAdd pdf2word exe,"def predictAndSave(self, imgs, img_name):\r\n ...",https://github.com/PaddlePaddle/PaddleOCR.git,Python,...,25,0,,Convention,307,"[822, 8500, 2855, 11371, 29898, 1311, 29892, 5...","[(<PRE>, 0.7492886185646057), (module, 0.47944...","[(<s>, 6.321602312800434e-13), ($}, 1.21012630...","[(def, 0.0007611338514834642), (predict, 0.000...",1.381488
3,278875,3613c3defc39c236fb1592c4f7ba1a9cc887343a,keras,keras/mixed_precision/loss_scale_optimizer_tes...,loss_scale_optimizer_test.py,testHyperParametersExposed,Remove pylint comments.\n\nPiperOrigin-RevId: ...,def testHyperParametersExposed(self):\n ...,https://github.com/keras-team/keras.git,Python,...,30,73,# LossScaleOptimizer and hyperpara...,Convention,523,"[822, 1243, 26322, 546, 11507, 1252, 4752, 298...","[(<PRE>, 0.7492900490760803), (module, 0.47944...","[(<s>, 6.321457571810407e-13), ($}, 1.21011436...","[(def, 0.0007611316395923495), (test, 0.019638...",0.487210
4,152057,a6adc22f0711c8ab78c6ef8fc78715f815cc750f,stable-diffusion-webui,webui.py,webui.py,js,added interrupt button\nadded save button\n--a...,def js(self):\r\n obj = {\r\n ...,https://github.com/AUTOMATIC1111/stable-diffus...,Python,...,11,30,return json.dumps(obj),Convention,100,"[822, 6965, 29898, 1311, 1125, 30004, 13, 4706...","[(<PRE>, 0.749289870262146), (module, 0.479445...","[(<s>, 6.321889626376143e-13), ($}, 1.21010756...","[(def, 0.0007611394976265728), (js, 1.99369169...",1.183697

In [31]:
## Saving CheckPoint 2
dataframe_to_save.to_json(f"{output_dir}/raw_logits.json", index=False)

In [32]:
print("================================= PROCESS COMPLETED =================================")

================================= PROCESS COMPLETED =================================

In [33]:
del model
torch.cuda.empty_cache()
gc.collect()

352