## Analysis of Causal Results

In [1]:
def default_params(): 
    return {
        'input_path' : '/workspaces/CodeSmells/data/extension/causality/results',
        'output_plots' : '/workspaces/CodeSmells/notebooks/extension/causal_analysis/correlation_plots',
        'treatment' : 'T3',
    }
params = default_params()

### Imports

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [3]:
def create_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

### Dataset loading

In [4]:
# #code_smell_actual_prob_median, #code_smell_max_prob_median, #code_smell_min_prob_median, 
# #code_smell_actual_prob_mean, #code_smell_max_prob_mean, #code_smell_min_prob_mean, 
# #code_smell_psc_entropy, #code_smell_psc_relative,

####### results per smell, binary treatment 
causal_results_per_smell_dict = {
    'code_smell_psc_relative' : pd.read_json(f"{params['input_path']}/{params['treatment']}/code_smell_psc_relative.json"),
}
####### results all smells, binary treatment 
causal_results_dict = {
    'code_smell_psc_relative' : pd.read_json(f"{params['input_path']}/{params['treatment']}/code_smell_psc_relative_ALL.json"),
}
####### results per smell, categorical treatment 
causal_results_per_smell_categorical_dict = {
    'code_smell_psc_relative' : pd.read_json(f"{params['input_path']}/{params['treatment']}/categorical/code_smell_psc_relative.json"),
}
####### results all smell, categorical treatment 
causal_results_categorical_dict = {
    'code_smell_psc_relative' : pd.read_json(f"{params['input_path']}/{params['treatment']}/categorical/code_smell_psc_relative_ALL.json"),
}

In [5]:
causal_results_per_smell_dict['code_smell_psc_relative'].sort_values(by=['estimated_effect'], ascending=False)

,method_name,pearson_corr,spearman_corr,kendall_corr,estimated_effect,refutation_placebo_permute,refutation_unobserved_confounder,refutation_subset,intervention,s_msg_id
23,backdoor.propensity_score_weighting,0.556344,0.647788,0.529667,0.341951,"{'result': {'p_value': 0.86, 'is_statistically...","{'result': None, 'new_effect': [-0.0450111522,...","{'result': {'p_value': 1.0, 'is_statistically_...",M4,C0303
24,backdoor.generalized_linear_model,0.556344,0.647788,0.529667,0.341919,"{'result': {'p_value': 0.96, 'is_statistically...","{'result': None, 'new_effect': [-0.0455830975,...","{'result': {'p_value': 0.96, 'is_statistically...",M4,C0303
21,backdoor.propensity_score_matching,0.556344,0.647788,0.529667,0.341699,"{'result': {'p_value': 0.98, 'is_statistically...","{'result': None, 'new_effect': [-0.04007693370...","{'result': {'p_value': 0.88, 'is_statistically...",M4,C0303
22,backdoor.propensity_score_stratification,0.556344,0.647788,0.529667,0.340841,"{'result': {'p_value': 1.0, 'is_statistically_...","{'result': None, 'new_effect': [-0.0574779048,...","{'result': {'p_value': 0.9, 'is_statistically_...",M4,C0303
312,backdoor.propensity_score_matching,0.531165,0.540374,0.442199,0.315142,"{'result': {'p_value': 0.9, 'is_statistically_...","{'result': None, 'new_effect': [0.2898175812, ...","{'result': {'p_value': 0.6000000000000001, 'is...",M4,R0917
...,...,...,...,...,...,...,...,...,...,...
85,backdoor.propensity_score_matching,-0.199686,-0.206585,-0.169420,-0.252444,"{'result': {'p_value': 0.88, 'is_statistically...","{'result': None, 'new_effect': [-0.2737122208,...","{'result': {'p_value': 0.28, 'is_statistically...",M4,C0304
71,backdoor.propensity_score_weighting,-0.373184,-0.374796,-0.306251,-0.270670,"{'result': {'p_value': 0.9400000000000001, 'is...","{'result': None, 'new_effect': [-0.2714862622,...","{'result': {'p_value': 0.88, 'is_statistically...",M2,W0613
72,backdoor.generalized_linear_model,-0.373184,-0.374796,-0.306251,-0.270670,"{'result': {'p_value': 0.92, 'is_statistically...","{'result': None, 'new_effect': [-0.2748958829,...","{'result': {'p_value': 0.92, 'is_statistically...",M2,W0613
70,backdoor.propensity_score_matching,-0.373184,-0.374796,-0.306251,-0.274221,"{'result': {'p_value': 0.96, 'is_statistically...","{'result': None, 'new_effect': [-0.30457742860...","{'result': {'p_value': 0.98, 'is_statistically...",M2,W0613
28,backdoor.propensity_score_matching,-0.147770,-0.117591,-0.096131,-0.307325,"{'result': {'p_value': 0.84, 'is_statistically...","{'result': None, 'new_effect': [-0.3325376875,...","{'result': {'p_value': 0.12, 'is_statistically...",M3,C0415

In [6]:
causal_results_per_smell_dict['code_smell_psc_relative'].groupby(['intervention', 's_msg_id']).describe()

                      pearson_corr                                    \
                             count      mean           std       min
intervention s_msg_id
M2           C0103             3.0 -0.106989  1.699675e-17 -0.106989
             C0114             3.0 -0.171744  0.000000e+00 -0.171744
             C0116             3.0 -0.022291  0.000000e+00 -0.022291
             C0123             3.0 -0.084065  0.000000e+00 -0.084065
             C0200             3.0 -0.281616  0.000000e+00 -0.281616
...                            ...       ...           ...       ...
M4           W0718             3.0  0.004546  0.000000e+00  0.004546
             W0719             3.0 -0.130358  0.000000e+00 -0.130358
             W1309             3.0 -0.100957  0.000000e+00 -0.100957
             W1406             3.0 -0.061151  8.498375e-18 -0.061151
             W1514             3.0 -0.004189  0.000000e+00 -0.004189

                                                              spearman_corr  \
                            25%       50%       75%       max         count
intervention s_msg_id
M2           C0103    -0.106989 -0.106989 -0.106989 -0.106989           3.0
             C0114    -0.171744 -0.171744 -0.171744 -0.171744           3.0
             C0116    -0.022291 -0.022291 -0.022291 -0.022291           3.0
             C0123    -0.084065 -0.084065 -0.084065 -0.084065           3.0
             C0200    -0.281616 -0.281616 -0.281616 -0.281616           3.0
...                         ...       ...       ...       ...           ...
M4           W0718     0.004546  0.004546  0.004546  0.004546           3.0
             W0719    -0.130358 -0.130358 -0.130358 -0.130358           3.0
             W1309    -0.100957 -0.100957 -0.100957 -0.100957           3.0
             W1406    -0.061151 -0.061151 -0.061151 -0.061151           3.0
             W1514    -0.004189 -0.004189 -0.004189 -0.004189           3.0

                                 ... kendall_corr           estimated_effect  \
                           mean  ...          75%       max            count
intervention s_msg_id            ...
M2           C0103    -0.119518  ...    -0.097888 -0.097888              3.0
             C0114    -0.180244  ...    -0.147243 -0.147243              3.0
             C0116    -0.016593  ...    -0.013555 -0.013555              3.0
             C0123    -0.081060  ...    -0.066466 -0.066466              3.0
             C0200    -0.308205  ...    -0.251790 -0.251790              3.0
...                         ...  ...          ...       ...              ...
M4           W0718     0.045370  ...     0.037852  0.037852              3.0
             W0719    -0.137478  ...    -0.112384 -0.112384              3.0
             W1309    -0.088710  ...    -0.072818 -0.072818              3.0
             W1406    -0.043397  ...    -0.035606 -0.035606              3.0
             W1514    -0.000593  ...    -0.000488 -0.000488              3.0

                                                                         \
                           mean       std       min       25%       50%
intervention s_msg_id
M2           C0103    -0.063036  0.025081 -0.077517 -0.077517 -0.077517
             C0114    -0.036617  0.006848 -0.040571 -0.040571 -0.040571
             C0116    -0.001380  0.010936 -0.007694 -0.007694 -0.007694
             C0123    -0.027384  0.004076 -0.029737 -0.029737 -0.029737
             C0200    -0.027394  0.012314 -0.034504 -0.034504 -0.034504
...                         ...       ...       ...       ...       ...
M4           W0718     0.001777  0.000338  0.001387  0.001679  0.001972
             W0719    -0.016711  0.030743 -0.034461 -0.034461 -0.034461
             W1309    -0.031666  0.011786 -0.038471 -0.038471 -0.038471
             W1406    -0.019455  0.005480 -0.022618 -0.022618 -0.022618
             W1514    -0.010445  0.015546 -0.028396 -0.014932 -0.001469


                            75%       max
intervention s_msg_id
M2           C0103    -0.055796 -0.034075
             C0114    -0.034641 -0.028710
             C0116     0.001777  0.011247
             C0123    -0.026207 -0.022678
             C0200    -0.023839 -0.013175
...                         ...       ...
M4           W0718     0.001972  0.001972
             W0719    -0.007836  0.018788
             W1309    -0.028264 -0.018057
             W1406    -0.017873 -0.013127
             W1514    -0.001469 -0.001469

[123 rows x 32 columns]

### Plots

In [7]:
def plot_correlations(causal_df, outcome, correlation, method_name, output_dir, intervention = None):
    # Transforming the DataFrame using melt
    causal_df = causal_df[
        (causal_df['method_name'] == method_name)].copy()
    if intervention:
        causal_df = causal_df[
            (causal_df['method_name'] == method_name) &(causal_df['intervention'] == intervention)
        ].copy()
    correlation_plot_df = causal_df.melt(id_vars=['s_msg_id'], value_vars=[correlation, 'estimated_effect'],  var_name='type', value_name='value')

    # Create the plot
    plt.figure(figsize=(40, 6))
    barplot = sns.barplot(
        palette='mako',
        data=correlation_plot_df,
        x="s_msg_id",
        y="value",
        hue="type",
        alpha=0.8,
        errorbar=None)

    # Improve x-axis readability
    plt.xlabel("Smell Id", fontsize=12)
    plt.ylabel("Value", fontsize=12)
    plt.title(f"{correlation} vs ATE. Outcome [{outcome}], Treatment [{intervention}]", fontsize=14)

    # Move the legend outside for clarity
    plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
    
    output_dir = f"{output_dir}/{params['treatment']}/{method_name}"
    if intervention:
        output_dir = f"{output_dir}/{params['treatment']}/{intervention}/{method_name}"

    create_folder(output_dir)
    plt.savefig(f"{output_dir}/{outcome}_{correlation}.png", bbox_inches="tight", dpi=300)
    plt.close()

In [8]:
def plot_correlations_binary_treatment(causal_results_per_smell_dict, method_names):
    for outcome, causal_df in causal_results_per_smell_dict.items():
        for correlation in ['pearson_corr', 'spearman_corr', 'kendall_corr']:
            for method_name in method_names:
                for intervention in causal_df['intervention'].unique():
                    plot_correlations(causal_df, outcome, correlation, method_name, '/workspaces/CodeSmells/notebooks/extension/causal_analysis/correlation_plots/binary_treatment', intervention)

In [9]:
def plot_correlations_categorical_treatment(causal_results_per_smell_dict, method_names):
    for outcome, causal_df in causal_results_per_smell_dict.items():
        for correlation in ['pearson_corr', 'spearman_corr', 'kendall_corr']:
            for method_name in method_names:
                    plot_correlations(causal_df, outcome, correlation, method_name, '/workspaces/CodeSmells/notebooks/extension/causal_analysis/correlation_plots/categorical_treatment')

In [10]:
method_names = ['backdoor.generalized_linear_model', 'backdoor.propensity_score_matching', 'backdoor.propensity_score_stratification', 'backdoor.propensity_score_weighting']

In [11]:
if params['treatment'] in ['T1', 'T2','T3', 'T4']:
    plot_correlations_binary_treatment(causal_results_per_smell_dict, method_names)

/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')

In [12]:
if params['treatment'] in ['T2', 'T3']:
    plot_correlations_categorical_treatment(causal_results_per_smell_categorical_dict, method_names)

/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')
/tmp/ipykernel_1026305/1812138605.py:28: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="Metrics", bbox_to_anchor=(1.05, 1), loc='upper left')