In [1]:
import pandas as pd
from ast_utils import get_ast_height

In [2]:
df=pd.read_csv('../../dataset/codesmell_dataset.csv')

In [3]:
df.head()

,Unnamed: 0,msg_id,line,column,end_line,end_column,code_smell,code,func_name,commit_id,...,n_whitespaces,complexity,n_ast_nodes,n_words,vocab_size,nloc,token_counts,n_identifiers,repository,year
0,0,C0103,1,0,1.0,12.0,def test_DFA(self):,def test_DFA(self):\n transitions = {\n...,test_DFA,87eae9a25751a13d4ef48860fffa4df0998356eb,...,356.0,1.0,515.0,119.0,64.0,29.0,264.0,16.0,algorithms,outputs-22
1,1,C0103,2,8,2.0,9.0,"A = [1, 2, 3, 3]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,...,177.0,1.0,207.0,67.0,28.0,11.0,165.0,11.0,algorithms,outputs-22
2,2,C0103,3,8,3.0,9.0,"B = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,...,177.0,1.0,207.0,67.0,28.0,11.0,165.0,11.0,algorithms,outputs-22
3,3,C0103,4,8,4.0,9.0,"C = [2, 3, 3, 4]",def test_array_sum_combinations(self):\n ...,test_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,...,177.0,1.0,207.0,67.0,28.0,11.0,165.0,11.0,algorithms,outputs-22
4,4,C0103,2,8,2.0,9.0,"A = [1, 2, 3, 3]",def test_unique_array_sum_combinations(self):\...,test_unique_array_sum_combinations,87eae9a25751a13d4ef48860fffa4df0998356eb,...,207.0,1.0,153.0,49.0,30.0,11.0,117.0,11.0,algorithms,outputs-22

In [4]:
df['ast_height'] = df['code'].apply(get_ast_height)

In [9]:
df['ast_errors'].unique()

array(['[]',
       '[\'[rf"\\\\{sym}" for sym in tex2uni])("sym"\', \'rf"\\\\{sym}" for sym in tex2uni])("sym\']',
       '[\'fig_test.text(0, .5, "$" + "".join(rf"\\\\{s}a" for s in short_accs) + "$")\\n    fig_ref.text(\\n        0, .5, "$" + "".join(fr"\\\\{l} a" for l in corresponding_long_accs) + "$")\', \'rf"\\\\{s}a" for s in short_accs) + "$")\', \'$\', \'$\', \'fr"\\\\{l} a\', \'$"\', \'$\']',
       "['SIGN', 'SIGN', 'SIGN']", "['await', 'await']", '["\'bold\',"]',
       '[\'\\\'\\\'\\\'\\n        if info["code"] != "A000000":\\n            log.e("[error] outdated iQIYI key")\\n            log.wtf("is your you-get up-to-date?")\\n\\n        self.title = info["data"]["vi"]["vn"]\\n        self.title = self.title.replace(\\\'\\\\u200b\\\', \\\'\\\')\\n\\n        # data.vp = json.data.vp\\n        #  data.vi = json.data.vi\\n        #  data.f4v = json.data.f4v\\n        # if movieIsMember data.vp = json.data.np\\n\\n        #for highest qualities\\n        #for http://www.iqiyi.com/v_19rrmmz5yw.html  not vp -> np\\n        try:\\n            if info["data"][\\\'vp\\\']["tkl"]==\\\'\\\' :\\n                raise ValueError\\n        except:\\n            log.e("[Error] Do not support for iQIYI VIP video.")\\n            exit(-1)\\n\\n        vs = info["data"]["vp"]["tkl"][0]["vs"]\\n        self.baseurl=info["data"]["vp"]["du"].split("/")\\n\\n        for stream in self.stream_types:\\n            for i in vs:\\n                if self.stream_to_bid[stream[\\\'id\\\']] == i[\\\'bid\\\']:\\n                    video_links=i["fs"] #now in i["flvs"] not in i["fs"]\\n                    if not i["fs"][0]["l"].startswith("/"):\\n                        tmp = getVrsEncodeCode(i["fs"][0]["l"])\\n                        if tmp.endswith(\\\'mp4\\\'):\\n                             video_links = i["flvs"]\\n                    self.stream_urls[stream[\\\'id\\\']] = video_links\\n                    size = 0\\n                    for l in video_links:\\n                        size += l[\\\'b\\\']\\n                    self.streams[stream[\\\'id\\\']] = {\\\'container\\\': stream[\\\'container\\\'], \\\'video_profile\\\': stream[\\\'video_profile\\\'], \\\'size\\\' : size}\']',
       "['x.device']", '[\'"""\\n@\']',
       '[\'"""\', "Let\'s train our model using mini-batch gradient with a custom training loop.\\n\\nIn JAX, gradients are computed via *metaprogramming*: you call the `jax.grad` (or\\n`jax.value_and_grad` on a function in order to create a gradient-computing function\\nfor that first function.\\n\\nSo the first thing we need is a function that returns the loss value.\\nThat\'s the function we\'ll use to generate the gradient function. Something like this:\\n\\n```python", \'a custom training loop.\\n\\nIn\', \'are computed via\', \': you call the\', \'or\\n`jax.value_and_grad` on a\', \'`jax\', \'`\', \'order to create a\', \'function\', "that first function.\\n\\nSo the first thing we need is a function that returns the loss value.\\nThat\'s the function we\'ll use to generate the gradient function. Something like this:\\n\\n`", \'`\']',
       '[\'code = fr"""\\nimport os\\nimport sys\\nsys.path = {repr(sys.path)}\']',
       "['softmax']", "['x']",
       "['_, heads, q_len, _, k_len, is_cuda = *q.shape, k.shape[-2], q.is_cuda']",
       '[\'rf"Software\\\\Python\\\\PythonCore\\\\{sys.winver}"\\n                        r"\\\\Help\\\\Main Python Documentation"\', \'H\', \'M\']',
       "['*']", "[':d']", '[\'heuristics_line = f"""\']',
       '[\'r"""\\n    Save an offline version of this module\', \'a separate process.\\n\\n    The saved module serializes all of the\', \'attributes of this module\', \'can be loaded into the C\', \'API using\\n    ``torch::jit::load(filename)`` or into the\', \'`\', \'API with\', \'`torch.jit.load <torch.jit.load>`.\\n\\n    To be able to save a module, it must not make any calls to native\', \'be able to save a module, it must\', \'means that all submodules must be subclasses of\\n    :class:`ScriptModule` as well.\\n\\n    .. DANGER:\', \'..\', \'All modules, no matter their device, are always loaded onto the\', \'during loading.  This is different from :\', "\'s semantics", \'and may\', \'m: A :class:`ScriptModule` to save.\\n        f: A\', \'like\', \'has to implement\', \'a\', \'a file name\', \'from filename to contents which will be stored as part of\', \'..\', \':\\n        torch.jit.save attempts to preserve the behavior of some\', \'across versions. For example, dividing two integer tensors in\\n        PyTorch 1.5 performed floor division, and if the module\\n        containing that code is saved in PyTorch 1.5 and loaded in PyTorch 1.6\\n        its division behavior will be preserved. The same module saved in\\n        PyTorch 1.6 will fail to load in PyTorch 1.5, however, since the\\n        behavior of division changed in 1.6, and 1.5 does not know how to\\n        replicate the 1.6 behavior.\\n\\n    Example:\', \'two integer tensors\', \'PyTorch 1.5 performed floor\', \'the module\\n        containing that\', \'1.5\', \'PyTorch 1.6\\n        its division behavior will be preserved. The same module\', \'1.6 will fail to load\', \'PyTorch 1.5, however, since the\\n        behavior of division\', \',\', \'1.5 does not know how to\\n        replicate the 1.6\', \'.. testcode::\']',
       "['op, dtype,', 'M, K, N,']",
       '[\'r"""Compute Cohen\\\'s\', \'a statistic that measures\', "annotator agreement.\\n\\n    This function computes Cohen\'s", \'a score that expresses the\', \'of agreement between two annotators on a classification problem. It is\\n    defined as\\n\\n    .. math::\\n        \\\\kappa =\', \'.. math::\\n        \\\\k\', \'k\', \'math:\', \'the empirical probability of agreement on the\', \'to any sample\', \'the observed agreement\', \'and :math:\', \'the expected agreement when both annotators assign labels randomly.\\n    :math:\', \':\', \'using a per\', \'annotator empirical prior over\']',
       '["filename = fR\'\\\\\\\\?\\\\{absfilepath}\'", "fR\'\\\\\\\\?\\\\{absfilepath}"]'],
      dtype=object)

In [13]:
target_error = '[\'[rf"\\\\{sym}" for sym in tex2uni])("sym"\', \'rf"\\\\{sym}" for sym in tex2uni])("sym\']'

In [14]:
df[df['ast_errors'] == target_error]

,Unnamed: 0,msg_id,line,column,end_line,end_column,code_smell,code,func_name,commit_id,...,complexity,n_ast_nodes,n_words,vocab_size,nloc,token_counts,n_identifiers,repository,year,ast_height
7977,7978,C0103,2,8,2.0,9.0,p = types.SimpleNamespace(),def __init__(self):\n p = types.SimpleN...,__init__,5392fc1996c133460d911abe7bc66a587d1fca51,...,5.0,2194.0,567.0,204.0,160.0,1257.0,75.0,matplotlib,outputs-22,25
7978,7979,R0915,1,0,1.0,12.0,def __init__(self):,def __init__(self):\n p = types.SimpleN...,__init__,5392fc1996c133460d911abe7bc66a587d1fca51,...,5.0,2194.0,567.0,204.0,160.0,1257.0,75.0,matplotlib,outputs-22,25